name: SubmitToP4Action
on:
  push:
    branches:
      - main
permissions: read-all
jobs:
  submit_to_p4:
    name: submit
    runs-on: self-hosted
    steps:
      - name: Submit to P4
        working-directory: ${{ github.workspace }}
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ' | ') }}
        run: |
          set -e
        
          p4 reconcile -ead ./...
        
          if p4 opened ./... | grep -q .; then
            p4 submit -d "[WhitakrPortfolio] $COMMIT_MESSAGES"
          else
            echo "Nothing to submit"
          fi
